import React,{useMemo,useState} from 'react';
import {Eye,FileDown,FileSpreadsheet,PencilLine,X} from 'lucide-react';
import {api} from '../../services/api.js';
import {annualRow,buildAnnualStatementReport,DEFAULT_ANNUAL_LABELS} from '../../services/reportService.js';
import {fmt,negativeClass} from '../../utils/money.js';
import {monthNames} from '../../app/constants.js';
const COLS=['month','b1','b2','b3','b6','b7','b10','b12','b13'];
function readLabels(raw){try{return {...DEFAULT_ANNUAL_LABELS,...JSON.parse(raw||'{}')}}catch{return {...DEFAULT_ANNUAL_LABELS}}}
export default function AnnualStatement({data,setData}){
  const years=[...new Set(data.periods.map(p=>Number(p.year)))].sort((a,b)=>b-a);const [year,setYear]=useState(years[0]||new Date().getFullYear());
  const [scope,setScope]=useState('overall');
  const [labels,setLabels]=useState(()=>readLabels(data.settings.annualStatementLabels));const [editKey,setEditKey]=useState(null);const [editValue,setEditValue]=useState('');
  const periods=useMemo(()=>data.periods.filter(p=>Number(p.year)===Number(year)).sort((a,b)=>a.month-b.month),[data.periods,year]);
  const branchId=scope==='overall'?null:Number(scope);const branch=branchId?data.branches.find(b=>b.id===branchId):null;
  const rows=periods.map(p=>annualRow(data,p,branchId));const totals=rows.reduce((a,r)=>{for(const k of COLS.slice(1))a[k]=(a[k]||0)+Number(r[k]||0);return a},{});
  const title=scope==='overall'?`إجمالي المنشأة — ${year}`:`${branch?.name||'الفرع'} — ${year}`;
  const html=()=>buildAnnualStatementReport(data,year,labels,branchId);const saveLabel=async()=>{const next={...labels,[editKey]:editValue.trim()||DEFAULT_ANNUAL_LABELS[editKey]};setLabels(next);setEditKey(null);setData(await api.saveSetting('annualStatementLabels',JSON.stringify(next)))};
  const header=(key)=><th key={key} onContextMenu={e=>{e.preventDefault();setEditKey(key);setEditValue(labels[key]||DEFAULT_ANNUAL_LABELS[key])}} title="كلك يمين لتعديل المسمى" className="annual-editable-head">{labels[key]||DEFAULT_ANNUAL_LABELS[key]}<PencilLine size={11}/></th>;
  return <div className="space-y-5"><div className="card p-4 flex items-center justify-between gap-4"><div><h2 className="font-extrabold text-lg">بيان الإقرار الضريبي المجمع</h2><p className="text-xs text-slate-400 mt-1">اختر السنة ثم اعرض المجمع فقط أو فرعًا واحدًا.</p></div><div className="flex gap-2 items-center flex-wrap"><select className="input !w-32 !py-2" value={year} onChange={e=>setYear(Number(e.target.value))}>{years.length?years.map(y=><option key={y}>{y}</option>):<option>{year}</option>}</select><select className="input !w-52 !py-2" value={scope} onChange={e=>setScope(e.target.value)}><option value="overall">المجمع — جميع الفروع</option>{data.branches.filter(b=>b.active).map(b=><option key={b.id} value={String(b.id)}>{b.name}</option>)}</select><button className="btn btn-soft flex gap-2 items-center" onClick={()=>api.previewReport({html:html(),title:`بيان الإقرار ${title}`})}><Eye size={16}/>معاينة</button><button className="btn btn-soft flex gap-2 items-center" onClick={()=>api.exportPdf({html:html(),defaultName:`بيان-الإقرار-${scope==='overall'?'المجمع':branch?.name}-${year}.pdf`})}><FileDown size={16}/>PDF</button><button className="btn btn-soft flex gap-2 items-center" onClick={()=>api.exportExcel({html:html(),defaultName:`بيان-الإقرار-${scope==='overall'?'المجمع':branch?.name}-${year}.xls`})}><FileSpreadsheet size={16}/>Excel</button></div></div><div className="grid grid-cols-4 gap-3"><Kpi label="إجمالي المبيعات" value={totals.b6||0}/><Kpi label="إجمالي المشتريات والمصاريف" value={totals.b12||0}/><Kpi label="إجمالي ضريبة القيمة المضافة" value={totals.b13||0}/><Kpi label="عدد الإقرارات المسجلة" value={periods.length} money={false}/></div><StatementTable title={title} rows={rows} totals={totals} header={header}/>{editKey&&<div className="system-modal-backdrop"><div className="system-modal"><button className="system-modal-close" onClick={()=>setEditKey(null)}><X size={18}/></button><div className="system-modal-body"><h3>تعديل مسمى العمود</h3><p>سيتم حفظ المسمى الجديد واستخدامه في الجدول والمعاينة وPDF وExcel.</p><input className="input mt-3" value={editValue} autoFocus onChange={e=>setEditValue(e.target.value)} onKeyDown={e=>e.key==='Enter'&&saveLabel()}/></div><div className="system-modal-actions"><button className="btn btn-soft" onClick={()=>setEditKey(null)}>إلغاء</button><button className="btn btn-primary" onClick={saveLabel}>حفظ المسمى</button></div></div></div>}</div>
}
function StatementTable({title,rows,totals,header}){return <div className="card overflow-hidden"><div className="px-4 py-3 border-b font-extrabold bg-white">{title}</div><div className="overflow-auto"><table className="table w-full text-[11px] annual-screen-table"><thead><tr>{COLS.map(header)}</tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.period.id}>{COLS.map(k=><td key={k} className={k==='month'?'font-bold':`money ${negativeClass(r[k])}`}>{k==='month'?`${monthNames[r.month-1]} - ${r.period.year}`:fmt(r[k])}</td>)}</tr>):<tr><td colSpan={COLS.length} className="text-center text-slate-400 py-8">لا توجد إقرارات في هذه السنة</td></tr>}</tbody>{rows.length>0&&<tfoot><tr className="annual-total-row"><td>الإجمالي</td>{COLS.slice(1).map(k=><td key={k} className={`money ${negativeClass(totals[k])}`}>{fmt(totals[k])}</td>)}</tr></tfoot>}</table></div></div>}
function Kpi({label,value,money=true}){return <div className="card p-4"><div className="text-xs text-slate-400">{label}</div><div className={`text-xl font-extrabold mt-2 ${money?'money':''} ${money?negativeClass(value):''}`}>{money?fmt(value):value}</div></div>}
