import React,{useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {api} from '../../services/api.js';
import Field from '../../components/common/Field.jsx';
import Editable from '../../components/common/Editable.jsx';
export default function Branches({data,setData}){
  const [form,setForm]=useState({name:'',tax_number:'',address:'',category_id:''});
  const add=async()=>{if(!form.name.trim())return;setData(await api.addBranch({...form,category_id:form.category_id?Number(form.category_id):null}));setForm({name:'',tax_number:'',address:'',category_id:''})};
  const patch=async(b,key,val)=>setData(await api.updateBranch({...b,[key]:val}));
  return <div className="grid grid-cols-[360px_1fr] gap-5"><div className="card p-5"><h3 className="font-bold">إضافة فرع / نشاط</h3><p className="text-xs text-slate-400 mt-1 mb-4">بيانات الفرع تُحفظ محليًا. في المطبوعات يظهر الرقم الضريبي فقط.</p><Field label="اسم الفرع"><input className="input mb-3" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="الرقم الضريبي"><input className="input mb-3 money" value={form.tax_number} onChange={e=>setForm({...form,tax_number:e.target.value})}/></Field><Field label="العنوان"><input className="input mb-3" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></Field><Field label="تصنيف الفرع"><select className="input" value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">بدون تصنيف</option>{(data.categories||[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><button className="btn btn-primary w-full mt-3" onClick={add}><Plus size={16} className="inline ml-1"/>إضافة</button></div><div className="card overflow-auto"><table className="table w-full text-sm"><thead><tr><th>اسم الفرع</th><th>الرقم الضريبي</th><th>العنوان</th><th>تصنيف الفرع</th><th>الحالة</th><th></th></tr></thead><tbody>{data.branches.map(b=><tr key={b.id}><td><Editable value={b.name} onSave={v=>patch(b,'name',v)}/></td><td><Editable value={b.tax_number||''} onSave={v=>patch(b,'tax_number',v)}/></td><td><Editable value={b.address||''} onSave={v=>patch(b,'address',v)}/></td><td><select className="table-select" value={b.category_id||''} onChange={e=>patch(b,'category_id',e.target.value?Number(e.target.value):null)}><option value="">بدون تصنيف</option>{(data.categories||[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></td><td>{b.active?'نشط':'موقوف'}</td><td><button className="text-red-600" onClick={async()=>setData(await api.deleteBranch(b.id))}><Trash2 size={17}/></button></td></tr>)}</tbody></table></div></div>
}
