import React,{useState} from 'react';
import {api} from '../../services/api.js';
import {monthNames,statuses} from '../../app/constants.js';
import {toDisplayDate} from '../../utils/date.js';
import DateInput from '../../components/common/DateInput.jsx';
import ConfirmDialog from '../../components/common/ConfirmDialog.jsx';

function periodEmpty(data,p){
  const hasEntry=data.entries.some(e=>e.period_id===p.id&&Math.abs(Number(e.total||0))>0.000001);
  const hasAdj=data.adjustments.some(a=>a.period_id===p.id&&(Math.abs(Number(a.value||0))>0.000001||Math.abs(Number(a.tax_value||0))>0.000001));
  const pay=data.payments.find(x=>x.period_id===p.id);const hasPayment=!!pay&&(Math.abs(Number(pay.amount||0))>0.000001||pay.payment_date||pay.reference_no||pay.invoice_no||pay.note);
  const hasAttachments=data.attachments.some(a=>a.period_id===p.id);const hasReminders=data.reminders.some(r=>r.period_id===p.id);
  return !(hasEntry||hasAdj||hasPayment||hasAttachments||hasReminders);
}
export default function Periods({data,setData,activeId,setActiveId,setPage}){
  const now=new Date();const [year,setYear]=useState(now.getFullYear());const [month,setMonth]=useState(now.getMonth()+1);const [due,setDue]=useState('');const [confirm,setConfirm]=useState(null);
  const create=async()=>{const s=await api.createPeriod({year,month,label:`${monthNames[month-1]} ${year}`,dueDate:due});setData(s);const p=s.periods.find(x=>x.year===year&&x.month===month);if(p)setActiveId(p.id)};
  const askPaid=p=>setConfirm({kind:'paid',p,title:'تأكيد السداد',message:`سيتم تسجيل إقرار ${p.label} كإقرار تم سداده وقفل التعديل عليه.`,confirmText:'تأكيد السداد'});
  const askUnlock=p=>setConfirm({kind:'unlock',p,title:'فتح الإقرار للتعديل',message:`سيتم فتح إقرار ${p.label} للتعديل مع الاحتفاظ بحالة السداد وسجل التعديلات.`,confirmText:'فتح للتعديل'});
  const askDelete=p=>{
    if(p.status==='paid'||Number(p.is_locked)===1)return;
    if(!periodEmpty(data,p)){setConfirm({kind:'blocked',p,title:'لا يمكن حذف الإقرار',message:'الحذف متاح فقط للإقرار الفارغ تمامًا. هذا الإقرار يحتوي على بيانات أو مرفقات أو بيانات سداد.',confirmText:'حسنًا'});return}
    setConfirm({kind:'delete1',p,title:'تأكيد حذف الإقرار',message:`هل تريد حذف إقرار ${p.label}؟ الإقرار فارغ وسيتم الانتقال إلى خطوة التأكيد النهائي.`,confirmText:'متابعة الحذف'});
  };
  const executeConfirm=async()=>{const c=confirm;if(!c)return;if(c.kind==='blocked'){setConfirm(null);return}if(c.kind==='delete1'){setConfirm({kind:'delete2',p:c.p,title:'تنبيه: حذف نهائي',message:`سيتم الآن حذف إقرار ${c.p.label} نهائيًا من قاعدة البيانات. لا يمكن التراجع عن هذه العملية.`,confirmText:'حذف نهائي'});return}setConfirm(null);if(c.kind==='paid')setData(await api.updatePeriod({id:c.p.id,status:'paid',isLocked:true}));else if(c.kind==='unlock')setData(await api.updatePeriod({id:c.p.id,isLocked:false}));else if(c.kind==='delete2'){try{const s=await api.deletePeriod(c.p.id);setData(s);if(c.p.id===activeId)setActiveId(s.periods[0]?.id||null)}catch(err){setConfirm({kind:'blocked',title:'تعذر حذف الإقرار',message:err?.message||'لا يمكن حذف هذا الإقرار.',confirmText:'حسنًا'})}}};
  return <><div className="grid grid-cols-[360px_1fr] gap-5"><div className="card p-5"><h3 className="font-bold mb-4">إنشاء شهر جديد</h3><label className="text-xs text-slate-500">الشهر</label><select className="input mt-1 mb-3" value={month} onChange={e=>setMonth(Number(e.target.value))}>{monthNames.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select><label className="text-xs text-slate-500">السنة</label><input className="input mt-1 mb-3 money" value={year} onChange={e=>setYear(Number(e.target.value))}/><label className="text-xs text-slate-500">موعد الاستحقاق</label><DateInput className="input mt-1 mb-4" value={due} onChange={setDue}/><button className="btn btn-primary w-full" onClick={create}>إنشاء ونسخ القالب مع التصفير</button><p className="text-xs text-slate-400 mt-3 leading-6">الحسابات والأكواد ثابتة من دليل الحسابات، بينما القيم المالية تبدأ بصفر.</p></div><div className="card overflow-hidden"><table className="table w-full text-sm"><thead><tr><th>الفترة</th><th>الحالة</th><th>النسبة</th><th>الاستحقاق</th><th>الإجراءات</th></tr></thead><tbody>{data.periods.map(p=>{const paid=p.status==='paid';const locked=Number(p.is_locked)===1;const empty=periodEmpty(data,p);return <tr key={p.id} className={p.id===activeId?'bg-teal-50/60':''}><td className="font-bold">{p.label}</td><td>{statuses[p.status]}{locked&&<span className="text-xs text-slate-400 mr-2">مقفل</span>}</td><td>{p.tax_rate}%</td><td className="date-cell">{p.due_date?toDisplayDate(p.due_date):'-'}</td><td><div className="flex gap-2 flex-wrap"><button className="btn btn-soft !py-2" onClick={()=>{setActiveId(p.id);setPage('entry')}}>{locked?'معاينة':'فتح'}</button>{paid?<><button className="btn paid-status-btn !py-2" disabled>تم السداد</button><button className="btn btn-soft !py-2" onClick={()=>askUnlock(p)}>تعديل</button></>:<button className="btn btn-primary !py-2" onClick={()=>askPaid(p)}>سداد</button>}{!paid&&<button className={`btn btn-danger !py-2 ${!empty?'opacity-45 cursor-not-allowed':''}`} title={!empty?'الحذف متاح فقط للإقرار الفارغ تمامًا':''} onClick={()=>askDelete(p)}>حذف</button>}</div></td></tr>})}</tbody></table></div></div><ConfirmDialog open={!!confirm} title={confirm?.title} message={confirm?.message} confirmText={confirm?.confirmText} danger={confirm?.kind==='delete1'||confirm?.kind==='delete2'} onCancel={()=>setConfirm(null)} onConfirm={executeConfirm}/></>
}
