import React,{useState} from 'react';
import {api} from '../../services/api.js';
import {monthNames,statuses} from '../../app/constants.js';
import ConfirmDialog from '../../components/common/ConfirmDialog.jsx';
export default function Periods({data,setData,activeId,setActiveId,setPage}){
  const now=new Date();const [year,setYear]=useState(now.getFullYear());const [month,setMonth]=useState(now.getMonth()+1);const [due,setDue]=useState('');
  const [confirm,setConfirm]=useState(null);
  const create=async()=>{const s=await api.createPeriod({year,month,label:`${monthNames[month-1]} ${year}`,dueDate:due});setData(s);const p=s.periods.find(x=>x.year===year&&x.month===month);if(p)setActiveId(p.id)};
  const askPaid=p=>setConfirm({kind:'paid',p,title:'تأكيد السداد',message:`سيتم اعتبار إقرار ${p.label} مدفوعًا وقفل جميع التعديلات. يمكنك فتحه للتعديل لاحقًا عند الحاجة.`,confirmText:'تم الدفع'});
  const askUnlock=p=>setConfirm({kind:'unlock',p,title:'فتح الإقرار للتعديل',message:`سيتم فتح إقرار ${p.label} للتعديل وتسجيل العملية في سجل التعديلات.`,confirmText:'فتح للتعديل'});
  const askDelete=p=>setConfirm({kind:'delete',p,title:'حذف الإقرار الضريبي',message:`سيتم حذف إقرار ${p.label} نهائيًا مع قيوده ومرفقاته وبيانات السداد المرتبطة به. لا يمكن التراجع عن هذه العملية.`,confirmText:'حذف الإقرار'});
  const executeConfirm=async()=>{const c=confirm;if(!c)return;setConfirm(null);if(c.kind==='paid')setData(await api.updatePeriod({id:c.p.id,status:'paid',isLocked:true}));else if(c.kind==='unlock')setData(await api.updatePeriod({id:c.p.id,isLocked:false}));else if(c.kind==='delete'){const s=await api.deletePeriod(c.p.id);setData(s);if(c.p.id===activeId)setActiveId(s.periods[0]?.id||null)}};
  return <><div className="grid grid-cols-[360px_1fr] gap-5"><div className="card p-5"><h3 className="font-bold mb-4">إنشاء شهر جديد</h3><label className="text-xs text-slate-500">الشهر</label><select className="input mt-1 mb-3" value={month} onChange={e=>setMonth(Number(e.target.value))}>{monthNames.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select><label className="text-xs text-slate-500">السنة</label><input className="input mt-1 mb-3 money" value={year} onChange={e=>setYear(Number(e.target.value))}/><label className="text-xs text-slate-500">موعد الاستحقاق</label><input type="date" className="input mt-1 mb-4" value={due} onChange={e=>setDue(e.target.value)}/><button className="btn btn-primary w-full" onClick={create}>إنشاء ونسخ القالب مع التصفير</button><p className="text-xs text-slate-400 mt-3 leading-6">الحسابات والأكواد ثابتة من دليل الحسابات، بينما القيم المالية تبدأ بصفر.</p></div><div className="card overflow-hidden"><table className="table w-full text-sm"><thead><tr><th>الفترة</th><th>الحالة</th><th>النسبة</th><th>الاستحقاق</th><th>الإجراءات</th></tr></thead><tbody>{data.periods.map(p=>{const locked=Number(p.is_locked)===1;return <tr key={p.id} className={p.id===activeId?'bg-teal-50/60':''}><td className="font-bold">{p.label}</td><td>{statuses[p.status]}{locked&&<span className="text-xs text-slate-400 mr-2">مقفل</span>}</td><td>{p.tax_rate}%</td><td>{p.due_date||'-'}</td><td><div className="flex gap-2 flex-wrap"><button className="btn btn-soft !py-2" onClick={()=>{setActiveId(p.id);setPage('entry')}}>{locked?'معاينة':'فتح'}</button>{locked?<button className="btn btn-soft !py-2" onClick={()=>askUnlock(p)}>تعديل</button>:<button className="btn btn-primary !py-2" onClick={()=>askPaid(p)}>تم الدفع</button>}<button className="btn btn-danger !py-2" onClick={()=>askDelete(p)}>حذف</button></div></td></tr>})}</tbody></table></div></div><ConfirmDialog open={!!confirm} title={confirm?.title} message={confirm?.message} confirmText={confirm?.confirmText} danger={confirm?.kind==='delete'} onCancel={()=>setConfirm(null)} onConfirm={executeConfirm}/></>
}
