import React,{useState} from 'react';
import {api} from '../../services/api.js';
import {monthNames,statuses} from '../../app/constants.js';
export default function Periods({data,setData,activeId,setActiveId,setPage}){
  const now=new Date();const [year,setYear]=useState(now.getFullYear());const [month,setMonth]=useState(now.getMonth()+1);const [due,setDue]=useState('');
  const create=async()=>{const s=await api.createPeriod({year,month,label:`${monthNames[month-1]} ${year}`,dueDate:due});setData(s);const p=s.periods.find(x=>x.year===year&&x.month===month);if(p)setActiveId(p.id)};
  const markPaid=async p=>{if(!window.confirm(`سيتم اعتبار إقرار ${p.label} مدفوعًا وقفل جميع التعديلات. متابعة؟`))return;setData(await api.updatePeriod({id:p.id,status:'paid',isLocked:true}))};
  const unlock=async p=>{if(!window.confirm(`فتح إقرار ${p.label} للتعديل؟ سيتم تسجيل العملية في سجل التعديلات.`))return;setData(await api.updatePeriod({id:p.id,isLocked:false}))};
  return <div className="grid grid-cols-[360px_1fr] gap-5"><div className="card p-5"><h3 className="font-bold mb-4">إنشاء شهر جديد</h3><label className="text-xs text-slate-500">الشهر</label><select className="input mt-1 mb-3" value={month} onChange={e=>setMonth(Number(e.target.value))}>{monthNames.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select><label className="text-xs text-slate-500">السنة</label><input className="input mt-1 mb-3 money" value={year} onChange={e=>setYear(Number(e.target.value))}/><label className="text-xs text-slate-500">موعد الاستحقاق</label><input type="date" className="input mt-1 mb-4" value={due} onChange={e=>setDue(e.target.value)}/><button className="btn btn-primary w-full" onClick={create}>إنشاء ونسخ القالب مع التصفير</button><p className="text-xs text-slate-400 mt-3 leading-6">الحسابات والأكواد ثابتة من دليل الحسابات، بينما القيم المالية تبدأ بصفر.</p></div><div className="card overflow-hidden"><table className="table w-full text-sm"><thead><tr><th>الفترة</th><th>الحالة</th><th>النسبة</th><th>الاستحقاق</th><th>الإجراءات</th></tr></thead><tbody>{data.periods.map(p=>{const locked=Number(p.is_locked)===1;return <tr key={p.id} className={p.id===activeId?'bg-teal-50/60':''}><td className="font-bold">{p.label}</td><td>{statuses[p.status]}{locked&&<span className="text-xs text-slate-400 mr-2">مقفل</span>}</td><td>{p.tax_rate}%</td><td>{p.due_date||'-'}</td><td><div className="flex gap-2"><button className="btn btn-soft !py-2" onClick={()=>{setActiveId(p.id);setPage('entry')}}>{locked?'معاينة':'فتح'}</button>{locked?<button className="btn btn-soft !py-2" onClick={()=>unlock(p)}>تعديل</button>:<button className="btn btn-primary !py-2" onClick={()=>markPaid(p)}>تم الدفع</button>}</div></td></tr>})}</tbody></table></div></div>
}
