import React,{useEffect,useMemo,useState} from 'react';
import {Eye,FileDown,FileSpreadsheet,Calculator,X,Search} from 'lucide-react';
import {api} from '../../services/api.js';
import {fmt,negativeClass,parseExpression,expressionForDisplay,formatEditableExpression,expressionTotal} from '../../utils/money.js';
import {accountVisibleForBranch} from '../../services/visibility.js';
import {branchMetrics} from '../../services/vatCalculations.js';
import {buildBranchReport,buildOverallReport} from '../../services/reportService.js';
export default function EntryPage({data,period,branchId,setBranchId,setData}){
  const [section,setSection]=useState('purchase');const [q,setQ]=useState('');const [popup,setPopup]=useState(null);
  if(!period)return <div>أنشئ إقرار أولًا.</div>;
  const locked=Number(period.is_locked)===1;
  const branch=data.branches.find(b=>b.id===branchId)||data.branches.find(b=>b.active);
  const codeMap=Object.fromEntries(data.codes.filter(c=>c.branch_id===branch?.id).map(c=>[c.account_id,c]));
  const accounts=data.accounts.filter(a=>a.active&&a.section===section&&accountVisibleForBranch(a,branch)).filter(a=>{const c=codeMap[a.id]||{};const s=`${a.name} ${c.short_code||''} ${c.program_code||''}`.toLowerCase();return s.includes(q.toLowerCase())});
  const getEntry=(aid,rate)=>data.entries.find(e=>e.period_id===period.id&&e.branch_id===branch?.id&&e.account_id===aid&&e.rate_type===rate);
  const totalRate=rate=>accounts.reduce((s,a)=>s+Number(getEntry(a.id,rate)?.total||0),0);
  const metrics=branchMetrics(data,period,branch?.id); const pct=period.tax_rate;
  const branchHtml=()=>buildBranchReport(data,period,branch), overallHtml=()=>buildOverallReport(data,period);
  const reportName=(scope,ext)=>`${scope==='branch'?branch?.name:'إجمالي-الفروع'}-${period.label}.${ext}`.replace(/[\\/:*?"<>|]/g,'-');
  return <div className="space-y-4">
    {locked&&<div className="bg-amber-50 border border-amber-200 text-amber-800 rounded-xl px-4 py-3 text-sm font-bold">هذا الإقرار تم دفعه ومقفل للتعديل. يمكنك المعاينة والطباعة فقط. افتحه للتعديل من قسم الإقرارات الضريبية عند الحاجة.</div>}
    <div className="card p-3 report-toolbar"><div className="report-toolbar-title"><div className="font-bold">المعاينة والتصدير</div><div className="text-xs text-slate-400">معاينة قبل الطباعة أو تصدير مباشر</div></div><div className="report-actions"><span className="report-scope">الفرع الحالي</span><button className="mini-action" onClick={()=>api.previewReport({html:branchHtml(),title:`${branch?.name} — ${period.label}`})}><Eye size={15}/>معاينة</button><button className="mini-action" onClick={()=>api.exportPdf({html:branchHtml(),defaultName:reportName('branch','pdf')})}><FileDown size={15}/>PDF</button><button className="mini-action" onClick={()=>api.exportExcel({html:branchHtml(),defaultName:reportName('branch','xls')})}><FileSpreadsheet size={15}/>Excel</button><span className="report-divider"></span><span className="report-scope">إجمالي الفروع</span><button className="mini-action" onClick={()=>api.previewReport({html:overallHtml(),title:`إجمالي الفروع — ${period.label}`})}><Eye size={15}/>معاينة</button><button className="mini-action" onClick={()=>api.exportPdf({html:overallHtml(),defaultName:reportName('overall','pdf')})}><FileDown size={15}/>PDF</button><button className="mini-action" onClick={()=>api.exportExcel({html:overallHtml(),defaultName:reportName('overall','xls')})}><FileSpreadsheet size={15}/>Excel</button></div></div>
    <div className="card p-4 flex gap-3 items-center"><select className="input !w-64" value={branch?.id||''} onChange={e=>setBranchId(Number(e.target.value))}>{data.branches.filter(b=>b.active).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><div className="relative flex-1"><Search size={17} className="absolute right-3 top-3.5 text-slate-400"/><input className="input pr-10" placeholder="ابحث بالبيان أو الكود المختصر أو كود البرنامج..." value={q} onChange={e=>setQ(e.target.value)}/></div><button className={`btn ${section==='purchase'?'btn-primary':'btn-soft'}`} onClick={()=>setSection('purchase')}>المشتريات</button><button className={`btn ${section==='sales'?'btn-primary':'btn-soft'}`} onClick={()=>setSection('sales')}>الإيرادات</button></div>
    <div className="card overflow-hidden"><div className="px-5 py-4 border-b flex justify-between"><div><div className="font-bold">{section==='purchase'?'المشتريات / المصروفات':'الإيرادات / المبيعات'} — {branch?.name}</div><div className="text-xs text-slate-400 mt-1">يمكن كتابة أكثر من مبلغ بعلامة +، والقيم السالبة تُدخل بعلامة السالب.</div></div><span className="badge bg-slate-100 text-slate-600">{period.label}</span></div><table className="table w-full text-sm"><thead><tr><th>البيان</th><th className="w-32">كود مختصر</th><th className="w-36">كود البرنامج</th><th className="w-60 text-center">15%</th><th className="w-60 text-center">0%</th></tr></thead><tbody>{accounts.map(a=>{const c=codeMap[a.id]||{};return <tr key={a.id}><td className="font-semibold">{a.name}</td><td className="money text-slate-500">{c.short_code||'-'}</td><td className="money text-slate-500">{c.program_code||'-'}</td><td><MoneyCell disabled={locked} entry={getEntry(a.id,'15')} onSave={async parts=>setData(await api.saveEntry({periodId:period.id,branchId:branch.id,accountId:a.id,rateType:'15',parts}))} onPopup={()=>setPopup({title:`${a.name} — 15%`,entry:getEntry(a.id,'15')})}/></td><td><MoneyCell disabled={locked} entry={getEntry(a.id,'0')} onSave={async parts=>setData(await api.saveEntry({periodId:period.id,branchId:branch.id,accountId:a.id,rateType:'0',parts}))} onPopup={()=>setPopup({title:`${a.name} — 0%`,entry:getEntry(a.id,'0')})}/></td></tr>})}</tbody><tfoot><tr className="table-total font-bold"><td colSpan="3">الإجمالي</td><td className={`money ${negativeClass(totalRate('15'))}`}>{fmt(totalRate('15'))}</td><td className={`money ${negativeClass(totalRate('0'))}`}>{fmt(totalRate('0'))}</td></tr><tr className="table-grand-total font-extrabold"><td colSpan="3">إجمالي مجمع</td><td colSpan="2" className={`money text-blue-700 text-base ${negativeClass(totalRate('15')+totalRate('0'))}`}>{fmt(totalRate('15')+totalRate('0'))}</td></tr></tfoot></table></div>
    <div className="card overflow-hidden branch-tax-summary"><div className="branch-tax-title">ملخص الضريبة — {branch?.name}</div><table className="table w-full text-sm"><tbody><tr><td>إجمالي الإيرادات {pct}%</td><td className={`money font-bold ${negativeClass(metrics.sales15)}`}>{fmt(metrics.sales15)}</td><td>قيمة الضريبة</td><td className={`money font-bold ${negativeClass(metrics.outputTax)}`}>{fmt(metrics.outputTax)}</td></tr><tr><td>إجمالي المشتريات {pct}%</td><td className={`money font-bold ${negativeClass(metrics.purchase15)}`}>{fmt(metrics.purchase15)}</td><td>قيمة الضريبة</td><td className={`money font-bold ${negativeClass(metrics.inputTax)}`}>{fmt(metrics.inputTax)}</td></tr><tr className="tax-net-row"><td colSpan="3">صافي الضريبة (الضريبة المستحقة)</td><td className={`money font-extrabold ${negativeClass(metrics.netTax)}`}>{fmt(metrics.netTax)}</td></tr></tbody></table></div>
    {popup&&<BreakdownModal popup={popup} data={data} onClose={()=>setPopup(null)}/>}</div>
}
function MoneyCell({entry,onSave,onPopup,disabled=false}){const [v,setV]=useState(entry?.expression?expressionForDisplay(entry.expression):'');useEffect(()=>setV(entry?.expression?expressionForDisplay(entry.expression):''),[entry?.expression]);const commit=()=>{if(disabled)return;const parts=parseExpression(v);onSave(parts);setV(parts.map(fmt).join(' + '))};return <div className="relative"><input disabled={disabled} type="text" inputMode="decimal" className={`input !py-2 money pl-9 ${disabled?'bg-slate-100 cursor-not-allowed':''} ${expressionTotal(v)<0?'negative-number':''}`} placeholder="0.00" value={v} onChange={e=>!disabled&&setV(formatEditableExpression(e.target.value))} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter'){e.currentTarget.blur()}}}/>{entry?.expression?.includes('+')&&<button title="تفاصيل التجميع" onMouseDown={e=>e.preventDefault()} onClick={onPopup} className="absolute left-2 top-2.5 text-teal-700"><Calculator size={16}/></button>}</div>}
function BreakdownModal({popup,data,onClose}){const parts=popup.entry?data.entryParts.filter(p=>p.entry_id===popup.entry.id):[];return <div className="fixed inset-0 bg-black/25 grid place-items-center z-50"><div className="bg-white rounded-2xl shadow-2xl w-[420px] p-5"><div className="flex justify-between items-center"><h3 className="font-bold">{popup.title}</h3><button onClick={onClose}><X size={19}/></button></div><div className="mt-4 space-y-2">{parts.map((p,i)=><div key={p.id} className="flex justify-between bg-slate-50 rounded-xl px-4 py-2"><span>المبلغ {i+1}</span><span className={`money font-bold ${negativeClass(p.amount)}`}>{fmt(p.amount)}</span></div>)}<div className="flex justify-between border-t pt-3 mt-3 font-bold"><span>الإجمالي</span><span className={`money text-teal-700 ${negativeClass(popup.entry?.total)}`}>{fmt(popup.entry?.total)}</span></div></div></div></div>}

