import React,{useEffect,useState} from 'react';
import {Eye,FileDown,FileSpreadsheet,Save,Pencil} from 'lucide-react';
import {api} from '../../services/api.js';
import {fmt,negativeClass,cleanNum} from '../../utils/money.js';
import {calculateVatBoxes} from '../../services/vatCalculations.js';
import {buildVatReturnReport} from '../../services/reportService.js';
export default function ReturnView({data,period,setData}){
  const [editing,setEditing]=useState(true);
  useEffect(()=>setEditing(Number(period?.is_locked)!==1),[period?.id,period?.is_locked]);
  if(!period)return <div>لا يوجد إقرار.</div>;
  const boxes=calculateVatBoxes(data,period);const locked=Number(period.is_locked)===1;const readOnly=locked||!editing;const vatHtml=()=>buildVatReturnReport(data,period);const adj=n=>data.adjustments.find(x=>x.period_id===period.id&&Number(x.box_no)===n)||{};
  const labels={1:`المبيعات الخاضعة للنسبة الأساسية ${period.tax_rate}%`,2:'المبيعات التي تتحمل الدولة ضريبتها',3:'المبيعات الخاضعة للنسبة الصفرية',4:'الصادرات',5:'المبيعات المعفاة من الضريبة',7:`المشتريات الخاضعة للنسبة الأساسية ${period.tax_rate}%`,8:'الاستيرادات الخاضعة للضريبة المدفوعة عند الاستيراد',9:'الاستيرادات الخاضعة للاحتساب العكسي',10:'المشتريات الخاضعة للنسبة الصفرية',11:'المشتريات المعفاة من الضريبة'};
  const autoOnly=new Set([1,3,7,10]);
  const mkRow=n=>[n,labels[n],boxes[n].value,boxes[n].tax,autoOnly.has(n),boxes[n].mappedValue,boxes[n].mappedTax];
  const rows=[1,2,3,4,5,7,8,9,10,11].map(mkRow);
  const saveAdj=async(boxNo,key,val,base=0)=>{if(readOnly)return;if(boxNo===2&&key==='tax')return;const old=adj(boxNo);const adjustment=cleanNum(val)-Number(base||0);setData(await api.saveAdjustment({periodId:period.id,boxNo,value:key==='value'?adjustment:Number(old.value||0),taxValue:key==='tax'?adjustment:Number(old.tax_value||0),note:old.note||''}))};
  const saveAndLock=()=>{document.activeElement?.blur?.();setEditing(false)};
  const salesTotal=[1,2,3,4,5].reduce((s,n)=>s+boxes[n].value,0),purchaseTotal=[7,8,9,10,11].reduce((s,n)=>s+boxes[n].value,0),outTax=[1,2,3,4,5].reduce((s,n)=>s+boxes[n].tax,0),inTax=[7,8,9,10,11].reduce((s,n)=>s+boxes[n].tax,0);const corr=adj(14);const net=outTax-inTax+Number(corr.tax_value||0);
  return <div className="card overflow-hidden max-w-5xl mx-auto">{locked&&<div className="bg-amber-50 border-b border-amber-200 text-amber-800 px-5 py-3 text-sm font-bold">الإقرار مدفوع ومقفل — العرض للمعاينة والطباعة فقط.</div>}<div className="p-5 border-b flex justify-between items-center gap-4"><div><h2 className="font-bold text-lg">نموذج إقرار ضريبة القيمة المضافة</h2><div className="text-sm text-slate-400">{period.label} — البنود المربوطة بالحسابات تُرحل تلقائيًا من الفروع</div></div><div className="flex items-center gap-2 flex-wrap">{!locked&&(editing?<button className="btn btn-save-strong flex items-center gap-2" onClick={saveAndLock}><Save size={17}/>حفظ نموذج VAT</button>:<button className="btn btn-edit-strong flex items-center gap-2" onClick={()=>setEditing(true)}><Pencil size={17}/>تعديل نموذج VAT</button>)}<button className="btn btn-soft flex items-center gap-2" onClick={()=>api.previewReport({html:vatHtml(),title:`نموذج VAT — ${period.label}`})}><Eye size={16}/>معاينة</button><button className="btn btn-soft flex items-center gap-2" onClick={()=>api.exportPdf({html:vatHtml(),defaultName:`نموذج-VAT-${period.label}.pdf`})}><FileDown size={16}/>PDF</button><button className="btn btn-soft flex items-center gap-2" onClick={()=>api.exportExcel({html:vatHtml(),defaultName:`نموذج-VAT-${period.label}.xls`})}><FileSpreadsheet size={16}/>Excel</button><span className="badge bg-teal-50 text-teal-700">VAT {period.tax_rate}%</span></div></div><ReturnSection title="الضريبة على المبيعات" rows={rows.filter(r=>r[0]<=5)} onSave={saveAdj} locked={readOnly}/><TotalRow label="إجمالي المبيعات" value={salesTotal} tax={outTax}/><ReturnSection title="الضريبة على المشتريات" rows={rows.filter(r=>r[0]>=7)} onSave={saveAdj} locked={readOnly}/><TotalRow label="إجمالي المشتريات" value={purchaseTotal} tax={inTax}/><div className="grid grid-cols-[1fr_180px_180px] border-t bg-slate-50 items-center"><div className="p-4 font-bold">تصحيحات من الفترات السابقة</div><div className="p-3"><input disabled={readOnly} className={`input money !py-2 ${readOnly?'bg-slate-100':''} ${negativeClass(corr.value)}`} defaultValue={fmt(corr.value||0)} onInput={e=>e.currentTarget.classList.toggle('negative-number',cleanNum(e.currentTarget.value)<0)} onBlur={e=>!readOnly&&saveAdj(14,'value',e.target.value,0)}/></div><div className="p-3"><input disabled={readOnly} className={`input money !py-2 ${readOnly?'bg-slate-100':''} ${negativeClass(corr.tax_value)}`} defaultValue={fmt(corr.tax_value||0)} onInput={e=>e.currentTarget.classList.toggle('negative-number',cleanNum(e.currentTarget.value)<0)} onBlur={e=>!readOnly&&saveAdj(14,'tax',e.target.value,0)}/></div></div><div className="grid grid-cols-[1fr_360px] bg-[#dff4e7] border-t-2 border-emerald-300"><div className="p-5 font-extrabold">صافي الضريبة (الضريبة المستحقة)</div><div className={`p-5 money font-extrabold text-xl ${negativeClass(net)}`}>{fmt(net)} ر.س</div></div></div>
}
function ReturnSection({title,rows,onSave,locked=false}){return <><div className="bg-[#fff7a8] px-5 py-2 font-bold">{title}</div><div className="grid grid-cols-[54px_1fr_180px_180px] text-sm"><div className="contents font-bold text-slate-500"><div className="p-3 bg-slate-50">#</div><div className="p-3 bg-slate-50">البيان</div><div className="p-3 bg-slate-50">القيمة</div><div className="p-3 bg-slate-50">مبلغ الضريبة</div></div>{rows.map(([n,label,val,tax,auto,baseValue,baseTax])=>{const taxReadOnly=auto||locked||n===2;return <React.Fragment key={n}><div className="p-3 border-t text-slate-400">{n}</div><div className="p-3 border-t"><div>{label}</div>{(baseValue!==0||baseTax!==0)&&!auto&&<div className="text-[10px] text-teal-700 mt-1">يشمل ترحيلًا تلقائيًا من الحسابات المرتبطة</div>}{n===2&&<div className="text-[10px] text-slate-400 mt-1">بند بدون ضريبة — مبلغ الضريبة يظل صفرًا</div>}</div><div className="p-2 border-t">{auto||locked?<div className={`bg-blue-50 rounded-lg px-3 py-2 money ${negativeClass(val)}`}>{fmt(val)}</div>:<input className={`input money !py-2 ${negativeClass(val)}`} defaultValue={fmt(val)} onInput={e=>e.currentTarget.classList.toggle('negative-number',cleanNum(e.currentTarget.value)<0)} onBlur={e=>onSave(n,'value',e.target.value,baseValue)}/>}</div><div className="p-2 border-t">{taxReadOnly?<div className={`bg-blue-50 rounded-lg px-3 py-2 money ${negativeClass(tax)}`}>{fmt(n===2?0:tax)}</div>:<input className={`input money !py-2 ${negativeClass(tax)}`} defaultValue={fmt(tax)} onInput={e=>e.currentTarget.classList.toggle('negative-number',cleanNum(e.currentTarget.value)<0)} onBlur={e=>onSave(n,'tax',e.target.value,baseTax)}/>}</div></React.Fragment>})}</div></>}
function TotalRow({label,value,tax}){return <div className="grid grid-cols-[1fr_180px_180px] bg-blue-50 border-y font-bold"><div className="p-3">{label}</div><div className={`p-3 money ${negativeClass(value)}`}>{fmt(value)}</div><div className={`p-3 money ${negativeClass(tax)}`}>{fmt(tax)}</div></div>}
